version: '2'
services:
    puppy-app:
        image: puppy
        external_links:
            - puppy-mysql:mysql
            - puppy-elasticsearch:elasticsearch
            - kafka:kafka
            - zookeeper:zookeeper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/puppy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK-NODES=zookeeper
        ports:
            - 8080:8080
    puppy-mysql:
        extends:
            file: mysql.yml
            service: puppy-mysql
    puppy-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: puppy-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
